<h5 align="center">Teste</h5>

<h6>Quem procura</h6>
<table>
  <tr>
    <td>
      <a href="/buscador/inserir-senha">Assinar o Serviço</a>
    </td>
  </tr>
   <tr>
    <td>
       <a href="">Editar sua Busca</a>
    </td>
  </tr>

  <tr>
    <td>
       <a href="/manual/ajuda">Obter Ajuda</a>
    </td>
  </tr>

  <tr>
    <td>
       <a href="/manual/saibamais">Saiba Mais</a>
    </td>
  </tr>
</table>

<h6>Quem oferta</h6>
<table>
  <tr>
    <td>
      <a href="">Assinar o Serviço</a>
    </td>
  </tr>
   <tr>
    <td>
       <a href="">Editar Ofertas</a>
    </td>
  </tr>
  <tr>
    <td>
       <a href="">Obter Ajuda</a>
    </td>
  </tr>
</table>

<?php?>
